exports.appString = {
  USER_CREATED: "User registered successfully",
  LOGIN_SUCCESS: "Login successful",
  INVALID_CREDENTIALS: "Invalid credentials",
  LOGOUT_SUCCESS: "Logged out successfully",
  USER_UPDATED: "User updated successfully",
  USER_DELETED: "User Soft deleted successfully",
  REGISTRATION_FAILED: "Registration Failed",
  Required_EmailPass: "emailId and password are required",
  LOGIN_FAILED: "Login failed",
  NOT_FOUND: "User not found",
  SUCCESS: "SUCCESS",
  USER_LOGOUT: "user logout successfully",
  LOGIN_FIRST: "Please Login First",
  USER_FILE_UPLOADED: "File Uploaded Successfully",
  USER_FILE_INVALID: "File is Invalid",
  img_ERR: "Only image files are allowed!",
  jWTNOT_DEFINED: "JWT secrets not defined",
  TOKEN_EXPIRED: "Invalid or expired token",
  TOKEN_MISSING: "Token missing",
  ALREDY_EXIST: "Already Exists",
  ADDRESS_CREATED: "User Address Created Successfully",
  ADDRESS_FAILED: "failed to create user address",
  ANOT_FOUND: "Address Not Found",
  PRIMARY_ADDRESS_UPDATED: "Primary Address Updated Successfully",
  ADDRESS_REQUIRED: "Address is required",
  LONG: " must be at least 4 characters long",
  LIMIT: "Address cannot exceed 20 characters",
  USERNAME_REQUIRED: "Username is required",
  EMAIL_REQUIRED: "EMAIL is required",
  ADMIN_CREATED: "Admin Created Successfully",
  ADMINALREDY_REGISTER: "Admin is already registered",
  ADMINACCESS_DEINED: "Admin access denied",
  RETRIVE: "User list retrieved successfully",
  Unauthorized: "User ID not found in token",
  Forbidden: "Admin access required",
  Forbidden1: "User record not found",
  SESSIONEXPIRED: "Session expired or logged in from another device",
  AUTHORIZATIONHEADERS: "Authorization header must start with Bearer",
  INVALIDREFRESHTOKEN: "Invalid refresh token",
  REFRESHREQUIRED: "Refresh token required",
  CHANGEPASSWORD: "Password changed successfully",
  INCORRECTPASSWORD: "Old password incorrect",
  RESETOTP: "Reset OTP",
  SENTOTP: "OTP sent to email",
  EXPIREDOTP: "expired OTP",
  RESETOTPSUCCESS: "Password reset successfully",
  DOESNOTMATCH: "New password and confirm password do not match",
  SERVICEUNAVAILABLE: "Email service unavailable",
  SMTPERROR: "SMTP Error",
  SENTSUCCESSFULLY: "Email sent successfully",
  CANNOTREACTIVATE: "Cannot reactivate: This user deleted their own account.",
  USERLISTRETRIVE: "User list retrieved successfully",
  INACTIVE: "User record not found or already inactive",
  REACTIVATE: "User reactivated successfully",
  INVALIDUSERID: "Invalid User ID format",
  ALREDYUSEPASSWORD:
    "This password was already used by you. Please choose a different one.",
  DELETDBYUSER: "Your account has been deleted by you. You cannot log in again",
  DELETEDBYADMIN:
    "Your account is deactivated by an admin. Please contact support",
  LOGOUT_FAILED: "lOGOUT FAILED SUCCESSFULLY",
  PARENTCATEGORY: "Parent category not found",
  SUBCATEGORYSUCCESS: "Subcategory created successfully",
  CATEGORYSUCCESS: "Category created successfully",
  CATEGORYFECTH: "Categories  fetched successfully",
  SUBCATEGORYNOTFOUND: "Subcategory not found",
  CATEGORYNOTFOUND: "Category name not found",
  PARENTCATEGORY: "Parent Category Not Found",
  PRODUCTCREATED: "Product Created Successfully",
  NOTSAME: "Category and Subcategory cannot be the same",
  CATEGORY_INACTIVE: "Main Category is inactive",
  SUBCATEGORY_INACTIVE: "Subcategory is inactive",
  NOT_A_SUBCATEGORY:
    "The provided ID is a Main Category, please provide a Subcategory ID",
  CART_ADDED: "Item added to cart successfully",
  CART_UPDATED: "Cart updated successfully",
  CART_EMPTY: "Cart is empty",
  CART_FETCHED: "Cart fetched successfully",
  CART_REMOVED: "Cart removed as it became empty",
  PRODUCT_NOT_FOUND: "Product not found",
  CART_NOT_FOUND: "Cart not found",
  ITEM_NOT_FOUND: "Item not found in cart",
  CART_ERROR: "Failed to process cart request",
  REQUIRED: "Product ID and quantity are required",

  REQUIRED: "Required fields are missing",
  PRODUCT_NOT_FOUND: "Product not found",
  CART_ADDED: "Item added to cart successfully",
  CART_UPDATED: "Cart updated successfully",
  CART_REMOVED: "Cart removed as it became empty",
  CART_NOT_FOUND: "Cart not found",
  ITEM_NOT_FOUND: "Item not found in cart",
  CART_ERROR: "An error occurred in the cart process",
  INVALID_ACTION: "Invalid action. Use 'inc' or 'dec'",
  NEGATIVE: "Negative values are not allowed",
  CARTEMPTY: "Cart is empty. Cannot create an order",
  ORDERINITLAIZE: " Order initialized successfully and cart cleared",
  SERVERERROR: "SEREVER ERROR",
  INVALID_PAYMENT_METHOD: "Invalid Payment Method",
  PRIMARYADDRESSNOTFOUND: "Primary address not found",
  PAYMENTMETHODUPDATED: "Payment method updated successfully",
  INVALIDPAYMENTMETHOD: "Invalid payment method selected",
  NOTCONFIGURED: "Payment settings not configured by admin",
  ORDERINTIATED: "Order initialized",
  CONTACT_REQUIRED: "Email or Mobile number is required",
  OTP_SENT: "OTP sent successfully.",
  OTP_RESENT: "OTP resent successfully",
  INVALID_OTP: "Invalid or expired OTP",
  VERIFIED_SUCCESS: "Account verified successfully.",
  NOT_VERIFIED: "Account not verified. Please verify your OTP first.",
  USER_NOT_FOUND: "User not found",
  ALREADY_EXISTS: "already exists",
  REQUIRED_FIELDS: "Contact info and OTP are required",
  EMAIL_ALREADY_VERIFIED: "Email can only be updated/verified once.",
  MOBILE_ALREADY_VERIFIED: "Mobile number can only be updated/verified once.",
  OTP_SENT_ONCE: "OTP sent. This is your one-time update.",
  USER_NOT_FOUND: "User not found or inactive",
  REQUIREDDATE: "Automatic promo codes require dates.",
  PROMOCODECREATED: "Promo code created successfully",
  PROMOCODEFETCHED: "Promo codes fetched successfully",
  PROMOCODENOTFOUND: "Promo code not found",
  PROMOCODEUPDATED: "Promo code updated successfully",
  PROMOCODEDELETED: "Promo code deleted successfully",
  PROMOCODEENABLED: "Promocode Enable Successfully",
  DATEVALIDATION: "Start date cannot be in the past. Please select today or a future date.",
  ENDDATE: "End date must be after the start date.",
 PLANCREATED: "Membership plan created and synced with Stripe",
 PLANUPDATED:"Membership Plan updated successfully",
 PLANNOTFOUND:"MembershipPlan  NOT FOUND",
 SUBSCRIPTIONPLANDEACTIVATED:"Subscription Plan deactivated successfully",
 SUBSCRIPTIONPLANREACTIVATED:"subscriptionPlan reactivated successfully",
 MEMBERSHIPIDNOTFOUND:"memebership id not found",
 MEMBERSHIP_NOT_EXISTS:"Mmebership Not exist",
 USER_ALREADY_MEMBERSHIP:"User Have Alredy Membership",
 SUB_CREATED:"Membership Created Successfully",
 MEMBERSHIPCOUMPSRY:"Membership is compulsory from your second order onwards. Please purchase a plan to continue.",
 ALREDYACTIVEMEMBERSHIP:"You already have an active membership.",
 ALREDYISEDPROMOCODE:"You have already used this manual promo code.",
 INVALIDMANUALPROMOCODE:"Invalid manual promo code.",
 ORDERFETCHED:"Order Fetched Successfully",
 PRODUCTACTIVATED:"Product reactivated successfully",
PRODUCTREACTIVATED:"Product deactivated successfully" ,
MEMBERSHIPNOTFOUND:"Membership Not Found",
NOACTIVE: "No active Stripe subscription found for this user.",
MEMBERSHIPCANCELLED:"Membership canceled and refund initiated.",
REFUNDDAILED:"Stripe Refund Failed",
WITHDRAWREQUEST:"Withdraw request created successfully.",
MAXIUMLIMIT:"Maximum 2 withdraw requests allowed per month.",
INSUFFICIENTREWARDPOINTS:"Insufficient reward points.",
ACTIVEMEMBERSHIPREQUIRED:"Active membership required.",
POINTSLIMIT:"Minimum 500 points required.",
PAYMENTSUCCESSORDERCONFIRMED:"Your payment was successful and Your order  is confirmed!",
SUBSCRIPTIONBUYSUCCESSFULL:"subscription buy successfully"
};

